[functions]
  external_node_modules = [ 
     "express",
     "bcrypt",
    "jsonwebtoken",
    "mongoose",
    "serverless-http",
    "swagger-ui-express",
    "swagger-jsdoc"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200