[functions]
 external_node_modules = ["express",
    "escape-html",
    "bcrypt",
    "jsonwebtoken",
    "mongoose",
    "serverless-http",
    "swagger-ui-express",
    "swagger-jsdoc"]
 node_bundler = 'esbuild'

 [[redirects]]
 force = true
 from = '/api/*'
 status = 200
 to = '/.netlify/functions/api/:splat'