[functions]
  external_node_modules = [ 
     "express",
    "escape-html",
     "bcrypt",
    "jsonwebtoken",
    "mongoose",
    "serverless-http"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200